name: Maven Release Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Optional: Import GPG Key for signing
    - name: Import GPG Key
      if: github.event_name == 'release' # Only for release events
      uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}

    - name: Build with Maven
      run: mvn clean install -B --file pax-sdk/pom.xml

    # Optionally, add a step to tag your release
    - name: Create Tag
      if: github.event_name == 'release'
      run: git tag ${{ github.event.release.tag_name }} && git push origin ${{ github.event.release.tag_name }}
